name: Build LibraryGUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild and Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0' # Visual Studio 2022

    - name: Install .NET Framework 4.8.1 SDK
      run: |
        choco install netfx-4.8.1-devpack -y
      shell: pwsh

    - name: Install C++/CLI support
      run: |
        choco install visualstudio2022-workload-vctools -y --package-parameters "--includeOptional --add Microsoft.VisualStudio.Component.VC.CLI.Support"
      shell: pwsh

    - name: Restore NuGet packages
      run: nuget restore LibraryGUI.vcxproj

    - name: Build the project
      run: msbuild LibraryGUI.vcxproj /p:Configuration=Release /p:Platform=x64 /p:CLRSupport=true /p:TargetFrameworkVersion=v4.8.1

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibraryGUI-Executable
        path: bin/Release/x64/LibraryGUI.exe
